repos:
  - repo: local
    hooks:
      - id: pipenv-run-format
        name: "Pipenv run format"
        language: system
        entry: pipenv run format
        pass_filenames: false
        types: [python]

      - id: pipenv-run-lint
        name: "Pipenv run lint"
        language: system
        entry: pipenv run lint
        pass_filenames: false
        types: [python]

      - id: pipenv-run-test
        name: "Pipenv run test"
        language: system
        entry: pipenv run test
        pass_filenames: false
        types: [python]
