name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup env file
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
        run: |
          echo "$ENV_FILE" > .env
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install
          pipenv install --dev
          pipenv install --dev tomli
      - name: Test code
        run: |
          pipenv run test
      - name: Lint code
        run: |
          pipenv run lint
      - name: Format code
        run: |
          pipenv run format
      - name: Close PR if tests or lint fail
        if: ${{ failure() }}
        uses: peter-evans/close-pull@v1
        with:
          comment: "Please ensure that lint checks and tests pass."

  publish-docker:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/log680-oxygen:${{ github.run_number }}
            ${{ secrets.DOCKER_USERNAME }}/log680-oxygen:latest
